matrix:
  include:
    - language: python
      python: 3.7
      before_script:
        - cd backend
      env:
        - FLASK_APP=wsgi.py
      script:
        - pip install -r requirements.txt
        - pytest
      
    