matrix:
  include:
    - language: python
      python: 
        - 3.7
      before_script:
        - export FLASK_APP="$TRAVIS_BUILD_DIR/backend/wsgi.py"
        - export FLASK_DEBUG=1
        - export APP_SETTINGS=configs.TestingConfig
        - pip install -r requirements.txt
      script:
        - pytest
      
    