version: '3'

services:

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=pacmandb
      
  frontend:
    image: frontend:latest
    build: ./frontend
    container_name: frontend
    ports:
      - 8081:8080

  backend:
    image: backend:latest
    build: ./backend/
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - .:/src
    ports:
      - 5000:5000
    depends_on:
      - db


volumes:
  postgres_data:



