version: '3'

services:

  frontend:
    image: frontend:latest
    build: ./frontend
    container_name: frontend
    ports:
      - 8081:8080

  backend:
    image: backend:latest
    build: ./backend/
    container_name: backend
    env_file:
    - ./backend/.env
    volumes:
    - .:/src
    ports:
    - 5000:5000




