version: '3'

services:

  backend:
    image: backend:latest
    build: ./backend/
    container_name: backend
    volumes:
      - .:/src
    ports:
      - 5000:5000
    depends_on:
      - db

  frontend:
    image: frontend:latest
    build: ./frontend
    container_name: frontend
    ports:
      - 8081:8080
  
  db:
    image: postgres:10.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432





