"""empty message

Revision ID: 3a705e2ea21a
Revises: aca52b38b25d
Create Date: 2019-12-03 09:51:17.302023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a705e2ea21a'
down_revision = 'aca52b38b25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('total_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'total_time')
    # ### end Alembic commands ###
