name: Docker Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build the Stack
        run: docker-compose up -d
      - name: Create Database
        run: docker-compose run backend flask db-migrate create-tables
      - name: Test
        run: docker-compose run backend pytest
      - name: Teardown
        run: docker-compose down
      - name: Clean
        run: docker system prune --all --force